apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-serial
spec:
  action: container-kill
  mode: one
  selector:
    pods:
      default:
        - frontend-7df479b46f-t2qbz
  containerNames:
    - server