apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: http-patch-head-serial
spec:
  selector:
    pods:
      default:
        - frontend-7df479b46f-t2qbz
  mode: one
  target: Request
  patch:
    body:
      - ['Token', 'none']
  port: 80
  path: '*'