apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-attr-serial
spec:
  action: attrOverride
  mode: one
  selector:
    pods:
      default:
        - redis-cart-76699746c5-8s7mq
  volumePath: /data
  path: /data/*
  attr:
    perm: 72
  percent: 50
  duration: "120s"