apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-delay-serial
spec:
  action: latency
  mode: one
  selector:
    pods:
      default:
        - redis-cart-76699746c5-8s7mq
  volumePath: /data
  path: /data/*
  delay: "100ms"
  percent: 10
  duration: "120s"