apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-mistake-serial
spec:
  action: mistake
  mode: one
  selector:
    pods:
      default:
        - redis-cart-76699746c5-8s7mq
  volumePath: /data
  path: /data/*
  mistake:
    filling: zero
    maxOccurrences: 1
    maxLength: 10
  methods:
    - READ
    - WRITE
  percent: 10
  duration: "120s"