apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-stress-memory-serial
spec:
  action: stress
  memType: "stack"
  selector:
    pods:
      default:
        - frontend-7df479b46f-t2qbz