apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-external-target-serial
spec:
  action: delay
  mode: one
  selector:
    pods:
      default:
        - frontend-7df479b46f-t2qbz
  delay:
    latency: "3000ms"
    correlation: "25"
    jitter: "90ms"
  direction: to
  externalTargets:
    - "8.8.8.8"
    - "8.8.0.0/16"
    - "114.114.114.114"
  duration: "120s"
