apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-target-serial-both
spec:
  action: delay
  mode: one
  selector:
    pods:
      default:
        - frontend-7df479b46f-t2qbz
  delay:
    latency: "3000ms"
    correlation: "25"
    jitter: "90ms"
  direction: both
  target:
    selector:
      namespaces:
        - default
      labelSelectors:
        app: "adservice"
    mode: one
  duration: "120s"
