apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-duplicate-serial
spec:
  action: duplicate
  mode: one
  selector:
    pods:
      default:
        - frontend-7df479b46f-t2qbz
  duplicate:
    duplicate: "90"
    correlation: "25"
  duration: "120s"