apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: stress-memory-serial
spec:
  mode: one
  selector:
    pods:
      default:
        - frontend-7df479b46f-t2qbz
  stressors:
    memory:
      workers: 4
      size: '512MB'
  duration: "120s"