{
 "title": "CBR-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_network_receive_packets_total{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_network_receive_packets_total{cluster=\"$cluster\",namespace=~\"$namespace\"}, pod)"
    }
   },
   { "name": "resolution", "query": "30s,5m,1h" },
   {
    "name": "host",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"mongodb_mongod_connections{cluster=~\\\"$cluster\\\"}|mongodb_up|mysql_up\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "mysql",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "mysql_global_status_table_open_cache_misses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_table_open_cache_misses{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_table_open_cache_overflows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "\r\nirate(mysql_global_status_table_open_cache_overflows{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_opened_files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_opened_files{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_table_open_cache_hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_table_open_cache_hits{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_handlers_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_handlers_total{instance=\"$host\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_qcache_not_cached",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_qcache_not_cached{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_bytes_received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_bytes_received{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_bytes_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_bytes_sent{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_table_locks_immediate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_table_locks_immediate{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_table_locks_waited",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_table_locks_waited{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_sort_scan",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_sort_scan{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_sort_merge_passes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_sort_merge_passes{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_sort_range",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_sort_range{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_sort_rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_sort_rows{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_select_range",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_select_range{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_select_full_range_join",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_select_full_range_join{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_select_full_join",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_select_full_join{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_created_tmp_files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_created_tmp_files{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_created_tmp_disk_tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_created_tmp_disk_tables{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_created_tmp_tables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_created_tmp_tables{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_questions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_questions{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_status_threads_running",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mysql_global_variables_max_connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "mysql_global_variables_max_connections{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "mysql_global_status_max_used_connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "mysql_global_status_threads_connected",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[5m]))"
      }
     ]
    },
    {
     "title": "mysql_global_status_queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "irate(mysql_global_status_queries{instance=\"$host\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "mongodb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "mongodb_extra_info_page_faults_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "irate(mongodb_extra_info_page_faults_total{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_op_counters_repl_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "irate(mongodb_op_counters_repl_total{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_asserts_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "irate(mongodb_asserts_total{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "mongodb_connections{instance=\"$host\", state=\"current\"}"
      }
     ]
    },
    {
     "title": "mongodb_mongod_metrics_record_moves_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "irate(mongodb_mongod_metrics_record_moves_total{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_mongod_metrics_cursor_open",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "irate(mongodb_mongod_metrics_cursor_open{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_mongod_metrics_query_executor_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "irate(mongodb_mongod_metrics_query_executor_total{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_mongod_metrics_query_executor_total/total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{instance=\"$host\", state=\"scanned_objects\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{instance=\"$host\", state=\"returned\"}[5m]))"
      }
     ]
    },
    {
     "title": "mongodb_mongod_global_lock_current_queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "irate(mongodb_mongod_global_lock_current_queue{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_mongod_metrics_document_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "irate(mongodb_mongod_metrics_document_total{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "mongodb_mongod_metrics_ttl_deleted_documents_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"$host\"}[5m]) "
      }
     ]
    },
    {
     "title": "mongodb_op_counters_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "irate(mongodb_op_counters_total{instance=\"$host\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_pod_container_status_restarts_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_fs_reads_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))"
      }
     ]
    },
    {
     "title": "container_fs_usage_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) "
      }
     ]
    },
    {
     "title": "container_fs_writes_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))"
      }
     ]
    },
    {
     "title": "container_fs_reads_total + container_fs_writes_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum (rate(container_fs_reads_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m]) + rate(container_fs_writes_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_network_receive_packets_dropped_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "container_network_transmit_packets_dropped_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "container_network_receive_packets_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_packets_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "container_network_transmit_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "container_network_receive_bytes_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg(irate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "container_network_transmit_packets_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "avg(irate(container_network_transmit_packets_total{pod!=\"\",namespace=~\"default\"}[5m])) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_cpu_usage_seconds_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[5m]) * 100)"
      }
     ]
    },
    {
     "title": "ontainer_cpu_usage_seconds_total/requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"})  / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "ontainer_cpu_usage_seconds_total/limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "container_memory_cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(container_memory_cache{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) "
      }
     ]
    },
    {
     "title": "container_memory_swap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(container_memory_swap{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "container_memory_working_set_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) by (pod)"
      }
     ]
    },
    {
     "title": "container_memory_working_set_bytes/requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "container_memory_working_set_bytes/limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "container_memory_rss/limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum (container_memory_rss{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"})/ sum(container_spec_memory_limit_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "container_memory_working_set_bytes/limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) / sum(container_spec_memory_limit_bytes{cluster=\"$cluster\",namespace=~\"$namespace\"}) * 100"
      }
     ]
    },
    {
     "title": "container_memory_rss",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}) "
      }
     ]
    }
   ]
  }
 ]
}